apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-11nnb0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-11nnb0
  namespace: my-nginx-11nnb0
  labels:
    name: nginx-11nnb0
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-11nnb0
  template:
    metadata:
      namespace: my-nginx-11nnb0
      labels:
        name: nginx-11nnb0
    spec:
      containers:
      - name: nginx-11nnb0
        image: nginx
        ports:
        - containerPort: 80

